local e=require"nixio.fs"
require("luci.tools.webadmin")
local e="mwan3 status | grep -c \"is online and tracking is active\""
local e=io.popen(e,"r")
local t=e:read("*a")
e:close()
m=Map("syncdial",translate("Multi-line multi-dial"),
translate("Create multiple virtual WAN ports using macvlan driver，Support concurrent multiple dialing <br /> Number of current online interfaces：")..t)
s=m:section(TypedSection,"syncdial",translate(" "))
s.anonymous=true
o=s:option(Flag,"enabled","Enable")
o.rmempty=false
o=s:option(Flag,"syncon","Enable concurrent multi-dial")
o.rmempty=false
o=s:option(ListValue,"dial_type",translate("Multi-dial type"))
o:value("1",translate("Single line multi-dial"))
o:value("2",translate("Two-line multi-dial"))
o.rmempty=false
o=s:option(Value,"wanselect",translate("Select external network interface"),translate("Specify the external network interface to be dialed, such as wan"))
luci.tools.webadmin.cbi_add_networks(o)
o.optional=false
o.rmempty=false
o=s:option(Value,"wannum","Number of virtual WAN interfaces")
o.datatype="range(0,249)"
o.optional=false
o.default=1
o=s:option(Flag,"bindwan","Binding a physical interface")
o.rmempty=false
o=s:option(Value,"wanselect2",translate("Select the second external network interface"),translate("<font color=\"red\">Specify the second external network interface to be dialed, such as wan2</font>"))
luci.tools.webadmin.cbi_add_networks(o)
o.optional=false
o:depends("dial_type","2")
o=s:option(Value,"wannum2",translate("Number of virtual WAN interfaces on the second line"),translate("Set the number of dials for the second line"))
o.datatype="range(0,249)"
o.optional=false
o.default=1
o:depends("dial_type","2")
o=s:option(Flag,"bindwan2","Binding a physical interface","The virtual interface generated by the second line is bound to the current physical interface")
o.rmempty=false
o:depends("dial_type","2")
o=s:option(Flag,"dialchk","Enable offline detection")
o.rmempty=false
o=s:option(Value,"dialnum","Minimum number of online interfaces","If the number of online interfaces is less than this value, redial.")
o.datatype="range(0,248)"
o.optional=false
o.default=2
o=s:option(Value,"dialnum2","Minimum number of online interfaces for the second line","If the number of online interfaces on the second line is less than this value, redial.")
o.datatype="range(0,248)"
o.optional=false
o.default=2
o:depends("dial_type","2")
o=s:option(Value,"dialwait","Redial wait time","When redialing, the waiting time before the next dial after all interfaces are offline. Unit: second Minimum: 5 seconds")
o.datatype="and(uinteger,min(5))"
o.optional=false
o=s:option(Flag,"old_frame","Create with old macvlan")
o.rmempty=false
o=s:option(Flag,"nomwan","Does not automatically configure MWAN3 load balancing","Users who need to customize load balancing settings or want to use policy routing")
o.rmempty=false
o=s:option(DummyValue,"_redial","Re-dial")
o.template="syncdial/redial_button"
o.width="10%"
return m
